export const CONFIRM_DIALOG_SHOW = 'CONFIRM_DIALOG_SHOW';
export type CONFIRM_DIALOG_SHOW = typeof CONFIRM_DIALOG_SHOW;

export const CONFIRM_DIALOG_HIDE = 'CONFIRM_DIALOG_HIDE';
export type CONFIRM_DIALOG_HIDE = typeof CONFIRM_DIALOG_HIDE;
