export const NOTIFICATION_DIALOG_SHOW = 'NOTIFICATION_DIALOG_SHOW';
export type NOTIFICATION_DIALOG_SHOW = typeof NOTIFICATION_DIALOG_SHOW;

export const NOTIFICATION_DIALOG_HIDE = 'NOTIFICATION_DIALOG_HIDE';
export type NOTIFICATION_DIALOG_HIDE = typeof NOTIFICATION_DIALOG_HIDE;